# Dockerfile.lightly
# Lightweight Linux container for lightly_train inference and finetuning.

FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install -r requirements_finetune.txt
