version: "3.3"
services:
  prefect:
    image: prefecthq/prefect:3.4.2-python3.11
    command: prefect server start
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${PREFECT_DB_USER}:${PREFECT_DB_PW}@prefect_db:5432/${PREFECT_DB_NAME} # Needed if using postgres and not sqlite
      # - PREFECT_UI_API_URL=https://localhost/api. needed if nginx is handling ssl termination
      - PREFECT_LOGGING_LEVEL=DEBUG
    ports:
      - 4200:4200
    depends_on:
      - prefect_db
    networks:
      mle_net:


  prefect_db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=${PREFECT_DB_USER}
      - POSTGRES_PASSWORD=${PREFECT_DB_PW}
      - POSTGRES_DB=${PREFECT_DB_NAME}
    volumes:
      - ./data/prefect_db:/var/lib/postgresql/data:rw
    restart: unless-stopped
    networks:
      mle_net:


  tiled:
    # see the file ./tiled/deploy/config.yml for detailed configuration of tiled
    image: ghcr.io/bluesky/tiled:0.2.0
    ports:
      - "8000:8000"
    environment:
      - TILED_DB_USER=${TILED_DB_USER}
      - TILED_DB_PW=${TILED_DB_PW}
      - TILED_DB_NAME=${TILED_DB_NAME}
      - TILED_DB_SERVER=${TILED_DB_SERVER}
      - TILED_SINGLE_USER_API_KEY=${TILED_SINGLE_USER_API_KEY}
    volumes:
      - ./tiled/deploy:/deploy
      - ./data/tiled_storage:/tiled_storage
    depends_on:
      - tiled_db
    networks:
      mle_net:


  tiled_db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=${TILED_DB_USER}
      - POSTGRES_PASSWORD=${TILED_DB_PW}
      - POSTGRES_DB=${TILED_DB_NAME}
    volumes:
      - ./data/tiled_db:/var/lib/postgresql/data:rw
      - ./data/tiled_storage:/tiled_storage
    restart: unless-stopped
    networks:
      mle_net:

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server
    command: >
      /bin/sh -c "
      envsubst < /basic_auth.ini.example > /basic_auth.ini &&
      exec mlflow server
      --backend-store-uri postgresql://${MLFLOW_DB_USER}:${MLFLOW_DB_PW}@mlflow_db:5432/${MLFLOW_DB_NAME}
      --host 0.0.0.0
      --port 5000
      --app-name basic-auth
      "
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      - MLFLOW_FLASK_SERVER_SECRET_KEY=${MLFLOW_FLASK_SERVER_SECRET_KEY}
      - MLFLOW_AUTH_CONFIG_PATH=/basic_auth.ini
    depends_on:
      - mlflow_db
    networks:
      - mle_net
    volumes:
      - ./data/mlflow_storage:/mlartifacts:rw
      - ./data/mlflow_auth:/mlflow_auth:rw
      - ./basic_auth.ini.example:/basic_auth.ini.example:ro

  mlflow_db:
    image: postgres:14.5-alpine  # Lightweight PostgreSQL version
    container_name: mlflow-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${MLFLOW_DB_USER}
      - POSTGRES_PASSWORD=${MLFLOW_DB_PW}
      - POSTGRES_DB=${MLFLOW_DB_NAME}
    volumes:
      - ./data/mlflow_db:/var/lib/postgresql/data:rw
    networks:
      - mle_net


  tiled_ingest:
    build:
      context: ./mlex_tiled_ingest
    profiles:
      - ingest
    environment:
      - TILED_DB_USER=${TILED_DB_USER}
      - TILED_DB_PW=${TILED_DB_PW}
      - TILED_DB_NAME=${TILED_DB_NAME}
      - TILED_DB_SERVER=${TILED_DB_SERVER}
      - TILED_INGEST_TILED_CONFIG_PATH=${TILED_INGEST_TILED_CONFIG_PATH}
      - TILED_INGEST_RMQ_HOST=${TILED_INGEST_RMQ_HOST}
      - TILED_INGEST_RMQ_USER=${TILED_INGEST_RMQ_USER}
      - TILED_INGEST_RMQ_PW=${TILED_INGEST_RMQ_PW}

    volumes:
      - ./mlex_tiled_ingest:/app
      - ./tiled/deploy:/deploy
      - ./data/tiled_storage:/tiled_storage

  mlex_segmentation:
    image: ghcr.io/mlexchange/mlex_highres_segmentation:main
    command: sh -c "python scripts/save_mlflow_algorithm.py || true && gunicorn -b 0.0.0.0:8075 --reload app:server"
    volumes:
      - ./data/annotations:/app/data
    environment:
      - EXPORT_FILE_PATH=/app/data/exported_annotation_data.json
      - DATA_TILED_URI=http://tiled:8000/api/v1/metadata/recons
      - DATA_TILED_API_KEY=${TILED_API_KEY}
      - MASK_TILED_URI=http://tiled:8000/
      - MASK_TILED_API_KEY=${TILED_API_KEY}
      - SEG_TILED_URI=http://tiled:8000/
      - SEG_TILED_API_KEY=${TILED_API_KEY}
      - USER_NAME=${MLEX_SEGM_USER}
      - USER_PASSWORD=${MLEX_SEGM_PW}
      - PREFECT_API_URL=http://prefect:4200/api
      - FLOW_NAME=${FLOW_NAME}
      - TIMEZONE=${TIMEZONE}
      # MLflow
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      # MLflow algorithm registration
      - MLFLOW_TRACKING_URI_OUTSIDE=${MLFLOW_TRACKING_URI}
      - ALGORITHM_JSON_PATH=/app/assets/models.json
    ports:
      - 8075:8075
    # depends_on:
    #   - tiled
    # Intermediate solution restarting frontend on failure due to connection issues
    restart: always
    networks:
      mle_net:

  lightly:
    build:
      context: ./scripts
      dockerfile: ../Dockerfile.lightly
    container_name: lightly
    environment:
      - MLFLOW_TRACKING_URI_OUTSIDE=http://mlflow:5000
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      - TILED_API_KEY=${TILED_SINGLE_USER_API_KEY}
      - DATA_TILED_URI_IMAGES=http://tiled:8000/api/v1/metadata/recons/42tiff
      - DATA_TILED_URI_MASKS=http://tiled:8000/api/v1/metadata/recons/42tiff_7classes_masks_tiff
      - MLFLOW_CACHE_DIR=/mlflow_cache
    volumes:
      - ./data/lightly_cache:/lightly_cache
      - ./data/mlflow_cache:/mlflow_cache
      - ./data/lightly_results:/results
      - ./scripts:/app
    depends_on:
      - mlflow
      - tiled
    networks:
      mle_net:
    profiles:
      - lightly

networks:
  mle_net:
    name: mle_net
    driver: bridge
